### ISSUE TITLE
Ошибка второй этаж, коридор, "осм запад"

### ISSUE THREAD

**Issue by Khaelenmore** [goraph/17rooms#12]
Вот такая ошибка вылезла

![Screenshot from 2021-05-05 23-56-13](https://user-images.githubusercontent.com/8182459/117201551-d1048e80-adfd-11eb-8d75-ae32d7d8d34a.png)

**Comment by goraph** [comment]
Пока не знаю как исправить не переписывая пол комнаты)

**Comment by goraph** [comment]
Спасибо, вроде исправил
