### ISSUE TITLE
Загадочные трусы

### ISSUE THREAD

**Issue by technix** [goraph/17rooms#13]
В самом начале игры на героине, очевидно, есть трусы. В инвентаре их не видно, но тем не менее:
![image](https://user-images.githubusercontent.com/303465/117202278-5126f600-adf6-11eb-8b93-c1f5f9b408f0.png)

**Comment by goraph** [comment]
Ну вот эти "Может быть", может быть стоит вообще отключить. Немного подумаю над этим.

**Comment by Oreolek** [comment]
Это подсказка инстеда (HINT_WORDS), если её отключить (`mplib.lua`, строки 135-144)) то парсер не будет предлагать альтернатив вообще.

На самом деле команда "открыть ящик руками" очевидно не должна работать, а если добавить руки (и другие части тела) как объект, то игроки попытаются делать ими вообще всё (пробить стену головой и всё в таком духе). Трусы в этом отношении выигрывают: ты ж явно не пойдёшь пробовать, к какому замку они подойдут.

**Comment by goraph** [comment]
Я уменьшил предложение альтернатив до ошибки во вводе в одну букву, по идее это должно решить эту и все схожие проблемы, но пока не закрываю.

**Comment by Oreolek** [comment]
Проблема решена, новых похожих багов не подавали, уже можешь закрыть

**Comment by goraph** [comment]
Да, согласен, пора закрывать
