### ISSUE TITLE
Объект "всё" не того рода

### ISSUE THREAD

**Issue by Zlobotrop** [goraph/17rooms#15]
![20210506_144534](https://user-images.githubusercontent.com/83765404/117296508-cf7aab00-ae7d-11eb-976c-e4d055cd6124.jpg)

Локация Гараж.

**Comment by goraph** [comment]
Если честно, исходя из контекста, и того как в данной комнате используется всё, я затрудняюсь определить правильный род для этого объекта. Ни одной реакции, которая однозначно заявляла о том или ином роде этого объекта я в файле игры не нашёл. Приму фикс если его пришлёт автор, если нет, будем считать что всё мужского рода в данной комнате - это авторское решение.
