### ISSUE TITLE
Кресло

### ISSUE THREAD

**Issue by btimofeev** [goraph/17rooms#22]
Если сесть в кресло, то пишет что ты находишься на кресле.

![Screenshot_20210511-224003.png](https://user-images.githubusercontent.com/1546407/118082832-8f0fb580-b3c6-11eb-8d7b-037d10289d14.png)

**Comment by goraph** [comment]
Не, это так и оставим. Это более-менее приемлемое поведение, в принципе ожидаемое от стандартной библиотеки, а фиксить очень сложно
