### ISSUE TITLE
Лампа и керосиновая лампа

### ISSUE THREAD

**Issue by btimofeev** [goraph/17rooms#23]
Если у нас есть керосиновая лампа, то обычную лампу в комнате (в гостиной например) нельзя осмотреть, пока керосиновую не выкинешь где-то в другой комнате.

![Screenshot_20210511-225455.png](https://user-images.githubusercontent.com/1546407/118083167-1f4dfa80-b3c7-11eb-9623-8425dc426c6a.png)

**Comment by goraph** [comment]
Спасибо, вроде все случаи дополнил синонимом с прилагательным. Пока закрываю
