### ISSUE TITLE
Ключ на чердаке открыт и доступен

### ISSUE THREAD

**Issue by Oreolek** [goraph/17rooms#27]
(С собой есть пирамидальный ключ)

> открыть дверцу 

Заперто. 

> открыть дверцу ключом 

Тут есть круглый ключ и пирамидальный ключ. 
*(так я узнаю что здесь лежит круглый ключ и он просто лежит)*

> взять круглый ключ 

Ты берёшь круглый ключ. (Счёт увеличился на 1)

**Comment by vvollo** [comment]
Круглый ключ торчит в дверце. Если дверца доступна, то и ключ доступен.
Ошибки тут не вижу.

**Comment by goraph** [comment]
Я тоже не вижу проблемы в том что ключ доступен. Адекватный способ узнать о его существовании тоже есть.

**Comment by vvollo** [comment]
Чтобы узнать о ключе, достаточно осмотреть дверцу.
Непонятно, что тут исправлять, так что закрываю.
