### ISSUE TITLE
подковёрная интрига

### ISSUE THREAD

**Issue by Oreolek** [goraph/17rooms#3]
```
> осмотреть под ковром
Ты не находишь под ковром ничего интересного.

> тянуть ковёр
[...], откинув край ковра, ты увидела […]
```

**Comment by goraph** [comment]
Имхо, это авторское решение, и такое править не надо. Автор решил превратить свою комнату в игру "угадай глагол", как и, если по честному, половина остальных авторов (плюс ещё встречаются варианты "угадай что надо осмотреть"), всё это исправить по большому счёту невозможно, да и не нужно. Если бы этот случай был выдающимся - другое дело. Но выглядит так, что абсолютное большинство участников пытались создать именно такую игру, а я в данном случае приверженец того, что надо максимально сохранять авторские решения. 

Нужная команда подбирается довольно быстро, это нетрудно, и, повторюсь, подобное есть в большинстве комнат, это делает игру цельной. 

Но я не против, если вы сделаете форк где пофиксите все подобные случаи.

**Comment by Oreolek** [comment]
Я за то, чтобы чинить. Потому что в другой комнате ковёр нельзя сдвинуть с места и надо под него смотреть.

**Comment by vvollo** [comment]
Проблема обходится с помощью моего пулл-реквеста (конечно, если Гораф его примет)

**Comment by vvollo** [comment]
Тот пулл-реквест не приняли, проблема не решена.

Распишу подробнее. Дефолтное сообщение крайне неудачное:
```
> осмотреть под ковром
Ты не находишь под ковром ничего интересного.
```
Что никак не является правдой.

По идее, в ответ на эту команду должна выдаваться фраза-отмазка, причем разная в трех случаях:
1. Если ковер просто лежит, и мы не знаем, что под ним.
2. Если край ковра отогнут, и нам видно пол.
3. Если мы уже видели, что под ковром, и потом вернули его на прежнее место.

Либо можно изощриться и придумать универсальный текст для всех трех случаев.
Если кто и может это придумать, то только автор комнаты)

**Comment by Oreolek** [comment]
Не отмазка, а подсказка. Более простое решение - это как раз сделать "посмотреть под ковром" синонимом "тянуть ковёр" и не дописывать новых реакций.

**Comment by vvollo** [comment]
Это-то понятно, но увы, по словам Горафа, автор комнаты категорически против такого решения. Поэтому и приходится изощряться.
Кстати, у меня еще идея. Можно пойти самым простым и банальным путем и написать фразу: "Вы не можете этого сделать". Тогда игрок решит, что это дефолтная фраза из стандартной библиотеки, и не будет предъявлять претензии)

**Comment by Oreolek** [comment]
Про автора Гораф ничего не писал, только что сам не хочет что-то менять за него.

> Тогда игрок решит, что это дефолтная фраза из стандартной библиотеки
Вот как раз "Ты не находишь под ковром ничего интересного." и есть дефолтная фраза из стандартной библиотеки.

**Comment by vvollo** [comment]
> Про автора Гораф ничего не писал

Мне в ЛС писал.

> Вот как раз "Ты не находишь под ковром ничего интересного." и есть дефолтная фраза из стандартной библиотеки.

Спасибо, Кэп.

**Comment by vvollo** [comment]
У меня еще идейка появилась)
А если на эту команду выдавать реакцию:
> И как это сделать?

Думаю, игрок поймет, что ему подсказывают, что он мыслит верно, но надо угадать глагол.

**Comment by vvollo** [comment]
Еще вариант (непонятно, почему сразу не пришел мне в голову). Вот такой код есть в описании самой комнаты:
```
if _"room14_glove".seen == false then
	p"Кажется, из-под ковра что-то торчит.";
else 
	p"Из-под ковра торчит перчатка горничной.";
end
```
Может, стоит в ответ на "см под ковром" выдавать эти же фразы.

**Comment by vvollo** [comment]
Исправлено после консультации с автором комнаты.
