### ISSUE TITLE
(Спальня) Простыня и кинжал

### ISSUE THREAD

**Issue by Oreolek** [goraph/17rooms#32]
> резать простыню кинжалом 

Твои руки недостаточно острые.

**Comment by goraph** [comment]
И на кухне авокадо наверное тоже надо чтоб было можно кинжалом нарезать

**Comment by Enolabutterfly** [comment]
Может проще сделать кинжал тупым?) Чтобы им ничего резать не получилось.

**Comment by Oreolek** [comment]
Так всё равно нужны реакции. Резать цветы, резать верёвки, резать ковры.

**Comment by Enolabutterfly** [comment]
"Кинжал слишком тупой, чтобы им что-то резать." Прописать в кинжале. С копать аналогично. Чем предусматривать индивидуальную реакцию для каждой комнаты.

**Comment by goraph** [comment]
А ты Энола видимо не прошла игру, раз предлагаешь такое решение)) Я думаю может что-то "кинжал не пригодится тебе в этой комнате", но подумаю ещё. Пока простого решения мне не видится, возможно придётся всё это делать

**Comment by vvollo** [comment]
Можно прописать что-нибудь вроде: "Ты не хочешь использовать мистический кинжал для столь низменных целей" при попытке резать/копать что-то не то)

**Comment by goraph** [comment]
> Можно прописать что-нибудь вроде: "Ты не хочешь использовать мистический кинжал для столь низменных целей" при попытке резать/копать что-то не то)
В принципе идея мне нравится, но не отговорит ли это игрока от попытки порезать кинжалам то что нужно для прохождения потом?

**Comment by vvollo** [comment]
На мой взгляд, те предметы, на которых нужно применять кинжал, достаточно магические, чтобы игрок попробовал.

**Comment by Oreolek** [comment]
Нет, это к тому что "низменные цели" это вообще не подсказка, что это должно означать?

**Comment by vvollo** [comment]
Там в половине комнат таинственная атмосфера, включая ту же спальню.
Можно поменять "низменных" на "бытовых".
И вообще, это должна быть не подсказка, а отмазка:)

**Comment by vvollo** [comment]
Я тут подумал: может, мы перемудрили?
Реально резать что-то может понадобиться, помимо тайной комнаты, только в трех местах:
* Спальня (простыня)
* Кухня (хлеб и авокадо)
* Столовая (булочка)

В спальне Дракон уже сделал, чтобы можно было.
В кухне можно выдавать сообщение типа: "Тут есть более подходящий для этого инструмент".
В столовой, наверное, надо позволить резать, но можно уточнить у автора комнаты.
В остальных случаях оставить сообщение по умолчанию, благо, оно вполне адекватное:
```
> резать стол кинжалом
Резать стол таинственным кинжалом бессмысленно.
```
С копанием еще проще. За всю игру ничего копать не может понадобиться даже гипотетически. Поэтому можно просто оставить дефолтное сообщение:
```
> копать землю кинжалом
Копать землю таинственным кинжалом бессмысленно.
```
Да и все)

**Comment by vvollo** [comment]
Исправлено именно этим способом.
