### ISSUE TITLE
пугало и халат

### ISSUE THREAD

**Issue by Oreolek** [goraph/17rooms#4]
( спасибо @technix )

пугало (room2) объявляет своим синонимом "халат"
халат (room8) отвечает на единственное слово "халат"

```
> взять халат
Мяч слишком далеко.
```

**Comment by goraph** [comment]
Проблема понятна, надо подумать как лучше исправить, спасибо.

**Comment by boscholeg** [comment]
Тоже наткнулся. Хотел взять халат, а в ответ мяч далеко.

**Comment by Enolabutterfly** [comment]
У пугала можно заменить в word запятые на |. А к халату добавить махровый в синонимы и сделать основным: "махровый халат".

**Comment by goraph** [comment]
Исправлено, спасибо
