### ISSUE TITLE
Орфографические ошибки в комнатах

### ISSUE THREAD

**Issue by Enolabutterfly** [goraph/17rooms#40]
Цифры в скобках - это количество таких слов.

Твоя горничная — это
Пролистав папку, ты обнаружила
Большелистый  (по смыслу правильнее широколистный)

комната | ошибки |  &nbsp; | &nbsp; | &nbsp;
-- | -- | -- | -- | --
main3.lua | экцентричная | марофона | &nbsp; | &nbsp;
room2.lua | большелистый | &nbsp; | &nbsp; | &nbsp;
room3.lua | остануться | интеллегентные | твоя горничная это | Врядли
room4.lua | панцыря (2) | &nbsp; | &nbsp; | &nbsp;
room7.lua | довольно таки (2) | &nbsp; | &nbsp; | &nbsp;
room8.lua | из лёгко проветриваемой | по гантеле | &nbsp; | &nbsp;
room12.lua | что-ли | &nbsp; | &nbsp; | &nbsp;
room14.lua | потерпшей | можноство | Пролистав папку ты  обнаружила
room15.lua | Статуетка | &nbsp; | &nbsp; | &nbsp;
room16.lua | твёрдным | тетё (3) | &nbsp; | &nbsp;
room17.lua | дурацая | &nbsp; | &nbsp; | &nbsp;

**Comment by goraph** [comment]
Вроде как всё это пофикшено реквестом вволло. Большелистный я считаю вообще не трогаем, это всё-таки авторский текст в игре в жанре фантастики, а не учебник по ботанике.
