### ISSUE TITLE
(спойлер) загадочный паркет

### ISSUE THREAD

**Issue by Oreolek** [goraph/17rooms#45]
> вскрыть паркет кинжалом

*(кинуть паркет)*
*(сначала взяв паркет)*
Паркет жёстко закреплён.

Вся остальная игра не понимает глагола `вскрыть`, так что думаю, что это спойлер.

**Comment by vvollo** [comment]
У меня выдает: "Непонятный глагол вскрыть". Где вы нашли такое?

**Comment by Oreolek** [comment]
Кажется, в таинственной комнате.

**Comment by goraph** [comment]
Хм, Ореолик, а это было в версии с дистанцией левенштейна в 2 символа или в 1? Я думаю это пофикшено вместе с "ключами и трусами", но пока не закрываю.

**Comment by vvollo** [comment]
Как оказалось, паркет тут ни при чем.

> вскрыть зеркало кинжалом
(кинуть зеркало)
(сначала взяв зеркало)
Зеркало невозможно взять.

> вскрыть манекен кинжалом
(кинуть манекен)
(сначала взяв манекен)
Манекен невозможно взять.

> вскрыть люстру кинжалом
(кинуть люстру)
(сначала взяв люстру)
Люстра жестко закреплена.

Но:
> вскрыть люстру
Непонятный глагол вскрыть.

**Comment by Enolabutterfly** [comment]
Вскрыть - вообще не распознаётся и вместо него можно писать любую абракадабру. Этот неизвестный глагол игнорируется. А "кинжалом" за счёт основы "кин" воспринимается как глагол "кинуть". Можно написать: "киноть" или любую неправильную версию и всё равно будет восприниматься как "кинуть".

**Comment by Oreolek** [comment]
Пересказывая обсуждение в дискорде, было проверено что баг исправлен в новой версии библиотеки метапарсера (2.2). Можно обновляться.
