### ISSUE TITLE
[Таинственная комната] стены

### ISSUE THREAD

**Issue by Oreolek** [goraph/17rooms#49]
В комнате спонтанно появляются стены.

**Comment by goraph** [comment]
Да, и что ты предлагаешь?) 
Они нужны только для достижения одной из концовок, у игроков вроде проблем в этом месте не возникает (возможно потому что по ходу всей игры стены постоянно то появляются, то исчезают от комнаты к комнате). Надо ли именно в этом месте что-то менять?

**Comment by Oreolek** [comment]
Предлагаю чтобы стены всё-таки существовали заранее? Просто в описании их нет. Можно даже дать возможность новой концовки.
