### ISSUE TITLE
[Таинственная комната] войти в нолик

### ISSUE THREAD

**Issue by Oreolek** [goraph/17rooms#50]
> войти в нолик

Ты не можешь зайти в то, что держишь в руках.

**Comment by goraph** [comment]
Ох. Я чёт пока прям не знаю даже как это исправить, не переделывая всю логику крестиков-ноликов, проблема не в этой команде, а то что нолик реально в руках (так реализовано автором), и там будет много подобного. 
Надо подумать.

**Comment by Oreolek** [comment]
Просто пропиши больше реакций для крестика и нолика, чтобы глагол "поставить _ в _" работал, а "войти в _" - нет.
