### ISSUE TITLE
[Кладовка] Несработавшие реакции

### ISSUE THREAD

**Issue by vvollo** [goraph/17rooms#53]
После выхода с острова, уже в кладовке, когда смотришь в зеркало, каждый раз выдается: "Меня закрутило, завертело и втянуло прямо в зеркало. Я снова оказалась в кладовке. Ну и чудеса..."
Кроме того, когда выходишь на восток в прихожую, по идее должна выдаться фраза: "Ты толкнула дверь и оказалась в прихожей. Оказывается здесь есть проход! Теперь ходить между помещениями будет куда удобней!" Но этого не происходит.

**Comment by Oreolek** [comment]
По-моему, это нормально как раз. Реакция на зеркало - есть. На новый выход - пусть реагирует игрок. Это не нужно прям разжёвывать.

**Comment by vvollo** [comment]
Дело в том, что эта фраза (здесь есть проход) прописана в коде комнаты. Но не выводится никогда.

**Comment by goraph** [comment]
В принципе эту фразу я добавил, а не автор, это мой баг) Я думал что будет непонятно, что между кладовкой и прихожей есть проход, который открывается только со стороны кладовки. 
Но раз уж вышло так, что она не выводится, и никто ни разу не жаловался... может она и не нужна вовсе?

**Comment by vvollo** [comment]
Ну, считай, что я жалуюсь)
Помнится, меня слегка выбило из колеи, когда я вдруг без предупреждения оказался в прихожей, хотя помнил, что с запада выхода нет.
