### ISSUE TITLE
[Терраса] Ключ доступен слишком рано

### ISSUE THREAD

**Issue by vvollo** [goraph/17rooms#56]
Можно, зайдя за дом, сразу посмотреть под плющом (что я и сделал), увидеть ключ и соответственно его взять. После этого на террасе делать нечего.
По идее, возможность посмотреть под плющом должна появиться только когда сбегаешь с террасы по ступенькам и замечаешь, что на земле под плющом что-то блестит.

**Comment by Oreolek** [comment]
По-моему, это не баг. Если игрок достаточно подкован, чтобы найти ключ раньше, то это хороший игрок. Прятать всё ради заскриптованной катсцены – хуже.

**Comment by vvollo** [comment]
Не считаю себя особо опытным игроком, тем не менее, нашел это сразу.
Но в принципе ты меня убедил.

**Comment by vvollo** [comment]
Ха!
Покопавшись в истории изменений, обнаружил, что изначально комната работала именно так, как я описал.
Но потом Гораф это пофиксил)
