### ISSUE TITLE
(Спальня) не начисляются очки за статуэтку

### ISSUE THREAD

**Issue by Enolabutterfly** [goraph/17rooms#65]
<img width="452" alt="Спальня 1" src="https://user-images.githubusercontent.com/21039847/129772165-730d3918-ffe8-47b8-b296-3413d0875bae.png">
<img width="467" alt="Спальня 2" src="https://user-images.githubusercontent.com/21039847/129772190-145966bd-80fe-4557-8395-89422fc925b7.png">

При этом на прохождении Блинова (Блинов играл в версию до коммита дракона)
<img width="299" alt="Прохождение Блинова" src="https://user-images.githubusercontent.com/21039847/129772371-cec9ffde-f428-4efd-aec4-6da35dae37bb.png">

Видео
https://youtu.be/cqZSTFgA4F0?t=23860

Файл с автоскриптом прохождения до нужного момента. (Расширение файла нужно удалить)
[autoscript.txt](https://github.com/goraph/17rooms/files/7001861/autoscript.txt)

После взятия статуэтки можно встать с кровати и пройти всю оставшуюся игру. 

Коммит Дракона от 15.06 с изменением поведения статуэтки. Возможно, это повлияло https://github.com/goraph/17rooms/commit/ab74392a0a177c9ec3bf46d5ae36d63772f8c200#diff-430a06003bd688ed62480fe0c9a4e5a6d2dcc962325cbe73166561a7ad4f1be9
![изображение](https://user-images.githubusercontent.com/21039847/129775287-c03230b5-7827-47d9-bcf2-03e05412bf49.png)

**Comment by goraph** [comment]
Спасибо, вроде должно быть исправлено
