### ISSUE TITLE
(Столовая) Булочка доступна сразу

### ISSUE THREAD

**Issue by vvollo** [goraph/17rooms#67]
Если зайти в столовую и сразу же ввести "осмотреть булочку", выведется ее описание. Манипуляции с верблюдом необязательны.
Вдобавок: на кнопку 5 можно нажимать неограниченное число раз, и верблюд каждый раз будет подходить к столу (хотя он уже там). По-моему, тут нужна реакция типа: "Больше эта кнопка ничего не делает".

**Comment by Enolabutterfly** [comment]
Можно и сломать сразу. Там вообще все предметы сразу доступны. В принципе на первое прохождение это никак не влияет, если игрок не знает, что вводить.

**Comment by goraph** [comment]
Не думаю что булочку стоит чинить. Вообще и я и автор знали о легкодоступности булочки ещё до релиза, и не посчитали что это надо чинить. 
С реакцией на кнопку пулл реквест приму)
