### ISSUE TITLE
рантайм баг с глаголом играть без аргументов

### ISSUE THREAD

**Issue by Enolabutterfly** [goraph/17rooms#8]
Это глобально по всей игре работает, если вводить "Играть" без аргументов, то выдаёт ошибку.
![image12121212](https://user-images.githubusercontent.com/21039847/117119263-3c714080-adab-11eb-800d-fa3144985d7e.png)

**Comment by Enolabutterfly** [comment]
А проблема в глаголе в Кладовке. Room 4

**Comment by goraph** [comment]
Исправлено, спасибо
